
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program/Cmake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:12 (project)"
    message: |
      The system is: Windows - 10.0.22000 - AMD64
